  name = "brentkirklandcom"
  authors = [""]
  description = ""
  language = "javascript"
  manifest_version = 2
  service_id = ""

[scripts]
  build = "bun build:c@e"

[local_server.backends.db]
  url = "http://"

